// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_YMfmTraWA-0M3Pc4rc5DCOAHqdpq8Sc',
    appId: '1:710066439408:web:086c5c13b87c6e23126e35',
    messagingSenderId: '710066439408',
    projectId: 'polygon-game',
    authDomain: 'polygon-game.firebaseapp.com',
    storageBucket: 'polygon-game.appspot.com',
    measurementId: 'G-XEMLB0ES95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3CxAUU1kujJIqLc9h6ykcV9XijbqfIVc',
    appId: '1:710066439408:android:874a5b20c7153b5b126e35',
    messagingSenderId: '710066439408',
    projectId: 'polygon-game',
    storageBucket: 'polygon-game.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlCPZGty4x45aRitdsbOSauNVWCkKSwsE',
    appId: '1:710066439408:ios:878e20b51656be29126e35',
    messagingSenderId: '710066439408',
    projectId: 'polygon-game',
    storageBucket: 'polygon-game.appspot.com',
    iosBundleId: 'com.example.circuleGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlCPZGty4x45aRitdsbOSauNVWCkKSwsE',
    appId: '1:710066439408:ios:878e20b51656be29126e35',
    messagingSenderId: '710066439408',
    projectId: 'polygon-game',
    storageBucket: 'polygon-game.appspot.com',
    iosBundleId: 'com.example.circuleGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_YMfmTraWA-0M3Pc4rc5DCOAHqdpq8Sc',
    appId: '1:710066439408:web:e0fa16d7fc606450126e35',
    messagingSenderId: '710066439408',
    projectId: 'polygon-game',
    authDomain: 'polygon-game.firebaseapp.com',
    storageBucket: 'polygon-game.appspot.com',
    measurementId: 'G-66ZHQ4LBXG',
  );
}
